name: Translate Issues

on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited]

permissions:
  issues: write
  pull-requests: write

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: dephraiim/translate-issues-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          translate-title: true
          translate-body: true
          translate-comment: true
          languages: ar,en
          default-languages: ar,en
